static const command step[] = {
	{ 200 },
	// Interactions with well and date reset
	{ B }, // wake up ctrl
	{ A }, // Tap well
	{ NORMAL_TAP },

	{ 40 },

	{ A }, // Scroll text
	{ NORMAL_TAP },

	{ 40 },

	{ A }, // Scroll text

	{ 120 },

	{ A }, // Invite
	{ NORMAL_TAP },

	{ 130 },

	{ HOME },
	{ 100 },

  // ADVANCE DATE - CURSOR SHOULD BE ON POKEMON GAME TO START
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },

	{ A },
	{ 40 },

	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },

	{ A },
	{ NORMAL_TAP },

	{ 20 },

	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },


	{ A },
	{ NORMAL_TAP },

	{ 20 },

	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },

	{ A },
	{ NORMAL_TAP },

	{ 20 },

	{ RIGHT },
	{ FAST_TAP },
	{ UP },
	{ FAST_TAP },

	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },


	{ A },
	{ 2*NORMAL_TAP },

	{ B },
	{ NORMAL_TAP },
	{ B },
	{ NORMAL_TAP },
	{ B },
	{ 2*NORMAL_TAP },

	{ UP },
	{ NORMAL_TAP },
	{ LEFT },
	{ NORMAL_TAP },
	{ LEFT },

	{ 70 },
	// END RESET DATE -- CURSOR IS ON POKEMON GAME

	// GAME SECTION
	{ A }, // Enter game
	{ 70 },

	{ B }, // Quit
	{ 100 },
	{ A }, // Confirm Quit

	{ 148 },
	// Fly from hills into hammerlock
	{ X }, // open menu
	{ 32 },
	{ A }, // select town map
	{ 240 },
	{ SHORT_UP }, // move cursor to hammerlock
	{ SHORT_LEFT },
	{ A }, // tap hammerlock FP
	{ 32 },
	{ A }, // tap FLY
	{ 200 }, // await load

	{ LONG_UP }, // into pokecenter
	{ 200 }, // await load

	// Use lotto interaction
	{ LONG_UP }, // walk up to lotto machine
	{ LEFT },
	{ 64 },
	{ A }, // engage
	{ 128 },
	{ A }, // engage
	{ 128 },
	{ DOWN }, // select lotto
	{ 200 },
	// MENU MASHING FOR REWARD...
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	{ A },
	{ 200 },
	// END MENU MASHING FOR REWARD...
	{ RIGHT }, // Exit pokecenter
	{ LONG_DOWN },
	{ 200 }, //wait for load

	// Fly from hammerlock into hills
	{ X }, // open menu
	{ 32 },
	{ A }, // select town map
	{ 240 },
	{ SHORT_DOWN }, // move cursor to hammerlock hills
	{ A }, // tap hammerlock hills FP
	{ 32 },
	{ A }, // tap hammerlock hills FLY
	{ 200 }, // wait load
	{ 128 },

	// walk to up well
	{ LONG_UP },
	{ LONG_UP },
	{ LONG_UP },
	{ LEFT },
	{ LONG_LEFT },
	{ LONG_LEFT },
	{ LONG_UP },
	{ LONG_UP },
	{ LONG_UP },
	{ LONG_UP },
	{ LONG_UP },
	{ LONG_UP },
	{ LONG_UP },
	{ UP },
};

static const command skip_step[] = {
	{ 256 },

	{ NORMAL_TAP },
	{ 80 },

	{ A }, // Tap well
	{ NORMAL_TAP },

	{ 40 },

	{ A }, // Scroll text
	{ NORMAL_TAP },

	{ 40 },

	{ A }, // Scroll text
	{ NORMAL_TAP },

	{ 100 },

	{ A }, // Invite
	{ NORMAL_TAP },

	{ 130 },

	{ HOME },
	{ NORMAL_TAP },

	{ 80 },

  // ADVANCE DATE - CURSOR SHOULD BE ON POKEMON GAME TO START
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ RIGHT },
	{ NORMAL_TAP },
	{ RIGHT },
	{ NORMAL_TAP },
	{ RIGHT },
	{ NORMAL_TAP },
	{ RIGHT },
	{ NORMAL_TAP },

	{ A },
	{ NORMAL_TAP },

	{ 20 },

	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },

	{ A },
	{ NORMAL_TAP },

	{ 20 },

	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },


	{ A },
	{ 40 },

	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },

	{ A },
	{ 40 },

	{ RIGHT },
	{ NORMAL_TAP },

	// START REPEAT_REDUCE_CYCLES
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	{ DOWN },
	{ NORMAL_TAP },
	// END REPEAT_REDUCE_CYCLES
	{ RIGHT },
	{ NORMAL_TAP },
	{ RIGHT },
	{ NORMAL_TAP },
	{ RIGHT },
	{ NORMAL_TAP },
	{ RIGHT },
	{ NORMAL_TAP },
	{ RIGHT },
	{ NORMAL_TAP },


	{ A },
	{ NOTHING, 2*NORMAL_TAP },

	{ B },
	{ NORMAL_TAP },
	{ B },
	{ NORMAL_TAP },
	{ B },
	{ NOTHING, 2*NORMAL_TAP },

	{ UP },
	{ NORMAL_TAP },
	{ LEFT },
	{ NORMAL_TAP },
	{ LEFT },
	{ 70 },
	// END RESET DATE -- CURSOR IS ON POKEMON GAME


	// GAME SECTION
	{ A }, // Enter game
	{ 70 },

	{ B }, // Quit
	{ 100 },
	{ A }, // Confirm Quit

	{ 255 },
	{ 150 },

	{ A }, // Tap well
	{ 120 },

	{ A }, // Invite
	{ 150 },

	{ HOME },
	{ 100 },

  // ADVANCE DATE - CURSOR SHOULD BE ON POKEMON GAME TO START
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },

	{ A },
	{ NORMAL_TAP },

	{ 20 },

	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },

	{ A },
	{ 40 },

	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },


	{ A },
	{ 40 },

	{ DOWN },
	{ FAST_TAP },
	{ DOWN },
	{ FAST_TAP },

	{ A },
	{ 40 },

	{ RIGHT },
	{ FAST_TAP },
	{ UP },
	{ FAST_TAP },

	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },
	{ RIGHT },
	{ FAST_TAP },


	{ A },
	{ 2*NORMAL_TAP },

	{ B },
	{ NORMAL_TAP },
	{ B },
	{ NORMAL_TAP },
	{ B },
	{ 2*NORMAL_TAP },

	{ UP },
	{ NORMAL_TAP },
	{ LEFT },
	{ NORMAL_TAP },
	{ LEFT },
	{ 70 },
	// END RESET DATE -- CURSOR IS ON POKEMON GAME

	// GAME SECTION
	{ A }, // Enter game
	{ 70 },

	{ B }, // Quit
	{ 100 },
	{ A }, // Confirm Quit
	{ NORMAL_TAP },
};
